import type { Metadata } from "next";
import { Lato, Poppins } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/utils/globalProvider";
import clsx from "clsx";

const lato = Lato({
  preload: true,
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-lato',
});

const poppins = Poppins({
  preload: true,
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '300', '400', '700', '900', '200', '500', '600', '800'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Material UI Next.js V15 App Router",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en"
      suppressHydrationWarning
      className={clsx(
        lato.variable,
        poppins.variable,
      )}
    >
      <head>
      </head>
      <body>
        <GlobalProvider>
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
